title: Coding ...
description: "A Code Recod Site"
author:
  name: "Yuqing Lin"
  email: "yqlinsci@gmail.com"
  url: "https://www.lin-sci.cn"

baseurl: https://www.lin-sci.cn/

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Yuqing Lin"
year : "2019"
